// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package cohorte

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addEleveToGroupe = `-- name: AddEleveToGroupe :exec
insert into eleve_groupe(num_etudiant, id_groupe)
    values ($1,$2)
`

type AddEleveToGroupeParams struct {
	NumEtudiant int32 `json:"num_etudiant"`
	IDGroupe    int32 `json:"id_groupe"`
}

func (q *Queries) AddEleveToGroupe(ctx context.Context, arg AddEleveToGroupeParams) error {
	_, err := q.db.Exec(ctx, addEleveToGroupe, arg.NumEtudiant, arg.IDGroupe)
	return err
}

const creationGroupe = `-- name: CreationGroupe :exec
INSERT INTO groupe (id, name, promo_id) 
    VALUES ($1, $2, $3) ON CONFLICT (id) DO UPDATE
SET
    name = EXCLUDED.name,
    promo_id = EXCLUDED.promo_id
`

type CreationGroupeParams struct {
	ID      int64       `json:"id"`
	Name    pgtype.Text `json:"name"`
	PromoID int64       `json:"promo_id"`
}

func (q *Queries) CreationGroupe(ctx context.Context, arg CreationGroupeParams) error {
	_, err := q.db.Exec(ctx, creationGroupe, arg.ID, arg.Name, arg.PromoID)
	return err
}

const creationPromotion = `-- name: CreationPromotion :exec
INSERT INTO promotion (id, name) 
    VALUES ($1, $2) ON CONFLICT (id) DO UPDATE
SET
    name = EXCLUDED.name
`

type CreationPromotionParams struct {
	ID   int64       `json:"id"`
	Name pgtype.Text `json:"name"`
}

func (q *Queries) CreationPromotion(ctx context.Context, arg CreationPromotionParams) error {
	_, err := q.db.Exec(ctx, creationPromotion, arg.ID, arg.Name)
	return err
}

const deleteEleveToGroupe = `-- name: DeleteEleveToGroupe :exec
delete from eleve_groupe
`

func (q *Queries) DeleteEleveToGroupe(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteEleveToGroupe)
	return err
}

const getGroupe = `-- name: GetGroupe :many
SELECT id, name, promo_id FROM groupe
    ORDER BY name
`

func (q *Queries) GetGroupe(ctx context.Context) ([]Groupe, error) {
	rows, err := q.db.Query(ctx, getGroupe)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Groupe
	for rows.Next() {
		var i Groupe
		if err := rows.Scan(&i.ID, &i.Name, &i.PromoID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPromotionById = `-- name: GetPromotionById :one
SELECT id, name FROM promotion where id = $1
`

func (q *Queries) GetPromotionById(ctx context.Context, id int64) (Promotion, error) {
	row := q.db.QueryRow(ctx, getPromotionById, id)
	var i Promotion
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const getPromotions = `-- name: GetPromotions :many
SELECT id, name FROM promotion
    ORDER BY name
`

func (q *Queries) GetPromotions(ctx context.Context) ([]Promotion, error) {
	rows, err := q.db.Query(ctx, getPromotions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Promotion
	for rows.Next() {
		var i Promotion
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateStudentPromo = `-- name: UpdateStudentPromo :exec
UPDATE public.student
SET promotion = $1
WHERE user_id = $2
`

type UpdateStudentPromoParams struct {
	Promotion pgtype.Text `json:"promotion"`
	ID        int32       `json:"id"`
}

func (q *Queries) UpdateStudentPromo(ctx context.Context, arg UpdateStudentPromoParams) error {
	_, err := q.db.Exec(ctx, updateStudentPromo, arg.Promotion, arg.ID)
	return err
}
