// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package user

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type User struct {
	ID      int32       `json:"id"`
	Version pgtype.Int4 `json:"version"`
	Name    string      `json:"name"`
	Surname string      `json:"surname"`
	Email   string      `json:"email"`
	Roles   pgtype.Text `json:"roles"`
	Blame   pgtype.Bool `json:"blame"`
}
